@startuml

enum LIBTYPE {
    TEXT,
    GRAPHIC,
    DEBUG
}

namespace ecs {
    ' using ComponentID = std::size_t
    ' using GroupID = std::string

    'inline ComponentID getNewComponentTypeID()
    'template <typename T> inline ComponentID getComponentTypeID() noexcept

    'inline GroupID getNewComponentTypeID()
    'inline GroupID getComponentTypeID(GroupID groupName) noexcept

    'constexpr std::size_t maxComponents = 32
    'constexpr std::size_t maxGroups = 64

    'using GroupBitset = std::bitset<maxGroups>
    'using ComponentBitSet = std::bitset<maxComponents>
    'using ComponentArray = std::array<ecs::AComponent*, maxComponents>

    class Universe {
        - std::vector<std::reference_wrapper<WorldManager>> _managers

        + Universe()
        + ~Universe()
        + void addWorldManager(WorldManager& world)
        + void delWorldManager()
    }

    class WorldManager {
        - World& _world
        - std::vector<std::reference_wrapper<ASystem>> _systems

        + WorldManager(World& _world)
        + ~WorldManager()
        + void addSystem(ASystem& system)
        + void init()
        + void update()
        + void render()
    }
    ecs.Universe <-- WorldManager

    class World {
        - std::vector<std::shared_ptr<Entity>> _entities
        - std::map<GroupID, std::vector<Entity*>> _groups

        + void refresh()
        + void addToGroup(Entity* entity, GroupID group)
        + std::vector<Entity*>& getGroup(GroupID group)
        + template<typename... TArgs> std::vector<Entity*>& getEntities()
        + Entity& addEntity()
    }
    ecs.WorldManager <-- World

    class Entity {
        - World& _world
        - bool _active = true
        - std::set<std::unique_ptr<AComponent>> _components {}
        - std::set<GroupID> _groups {}
        - ComponentBitSet _componentBitSet
        - ComponentArray _componentArray
        - GroupBitset _groupBitSet

        + Entity(World& world)
        + bool isActive()
        + void destroy()
        + template <typename T> bool hasComponent()
        + template <typename T, typename... TArgs> T& addComponent(TArgs&&... mArgs)
        + template <typename T> T& getComponent()
        + bool hasGroup(GroupID groupName)
        + void addGroup(GroupID groupName)
        + void delGroup(GroupID groupName)
    }
    ecs.World <-- Entity
    ecs.AComponent <-- Entity

    abstract AComponent {
        # Entity *_entity

        + virtual ~AComponent() = 0
    }
    ecs.Entity <-- AComponent

    interface IAnimation {
        + virtual ~IAnimation() = 0
        + virtual int frame() const = 0
        + virtual int speed() const = 0
        + virtual int index() const = 0
    }

    class Vector2d {
        + int x
        + int y
    }

    namespace component {
        class Transform {
            + Vector2d position

            + Transform()
            + ~Transform()
        }
        ecs.AComponent <|-- Transform

        class Motion {
            + Vector2d velocity
            + Vector2d acceleration

            + Motion()
            + ~Motion()
        }
        ecs.AComponent <|-- Motion

        class Size {
            + int w
            + int h

            + Size()
            + ~Size()
        }
        ecs.AComponent <|-- Size

        class Hitbox {
            + int w
            + int h

            + Hitbox()
            + ~Hitbox()
        }
        ecs.AComponent <|-- Hitbox

        abstract ARenderable {
            + virtual ~Renderable() = 0
            + virtual void setTexture(std::string name) = 0
            + virtual void setAnimation(std::string animationName, ecs::IAnimation animation) = 0
            + virtual std::string getCurrentAnimation() = 0
            + virtual void useAnimation(std::string animationName) = 0 
        }
        ecs.AComponent <|-- ARenderable

        class Follow {
            + Entity& followed

            + Follow(Entity& followed)
            + ~Follow()
        }
        ecs.AComponent <|-- Follow

        class AI {
            + AI()
            + ~AI()
        }
        ecs.AComponent <|-- AI

        class Input {
            + Input()
            + ~Input()
        }
        ecs.AComponent <|-- Input
    }

    abstract ASystem {
        + virtual ~ASystem() = 0
        + virtual void init() = 0
        + virtual void update() = 0
        + virtual void render() = 0
    }
    ecs.WorldManager <-- ASystem

    namespace system {
        ' Checks for collisions (use Transform and Hitbox)
        class Physics {
            + Physics()
            + ~Physics()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- Physics

        ' Allow player to be moved (use Motion and Joystick)
        abstract APlayer {
            + APlayer()
            + ~APlayer()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- APlayer

        ' Moves AI (use Motion and AI)
        abstract AAI {
            + AAI()
            + ~AAI()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- AAI

        ' Allow entity to follow another entity (use Motion and Follow)
        abstract AFollow {
            + AFollow()
            + ~AFollow()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- AFollow

        ' Update velocity and position (use Transform and Motion)
        class Movement {
            + Movement()
            + ~Movement()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- Movement

        ' Draws sprites to the screen (use ARenderable, Size and Transform)
        abstract AGraphics {
            + AGraphics()
            + ~AGraphics()
            + void init() override
            + void update() override
            + void render() override
        }
        ecs.ASystem <|-- AGraphics
    }
}

namespace graphical {
    interface IGraphical {
        + virtual ~IGraphical() = 0
        + virtual LIBTYPE getType() = 0
        + virtual ecs::component::ARenderable createRenderable(std::vector<std::string> paths, bool isAnimated = false) = 0
        + virtual ecs::IAnimation createAnimation(int index, int frame, int speed) = 0
    }

    abstract AGraphical {
        - LIBTYPE _type
        # Universe& _universe
    
        + AGraphical(LIBTYPE type, Universe& universe)
        + ~AGraphical() override
        + LIBTYPE getType() override
        + ecs::component::ARenderable createRenderable(std::vector<std::string> paths, bool isAnimated = false) override = 0
        + ecs::IAnimation createAnimation(int index, int frame, int speed) override = 0
    }
    IGraphical <|-- AGraphical

    class Animation {
        - int _frame
        - int _speed
        - int _index

        + Animation(int index, int frame, int speed)
        + ~Animation()
        + int frame() const override
        + int speed() const override
        + int index() const override
    }
    ecs.IAnimation <|-- Animation

    namespace sfml {
        class Graphical {
            + Graphical(Universe& universe)
            + ~Graphical()
            + LIBTYPE getType() override
            + ecs::component::ARenderable createRenderable(std::vector<std::string> paths, bool isAnimated = false) override
            + ecs::IAnimation createAnimation(int index, int frame, int speed) override
        }
        graphical.AGraphical <|-- Graphical

        namespace component {
            enum FLIPTYPE {
                NONE = 1,
                VERTICAL = 2,
                HORIZONTAL = 4
            }
            ' using SFML_Angle = float
            class Renderable {
                - sf::Texture* _texture
                - sf::Rect _srcRect, _destRect
                - FLIPTYPE _spriteFlip
                - SFML_Angle _angle
                - bool _animated
                - int _frame
                - int _speed
                - int _animIndex
                - std::map<std::string, ecs::IAnimation> _animations {}

                + Sprite(std::string name, bool isAnimated = false)
                + ~Sprite()
                + void setTexture(std::string name) override
                + void setAnimation(std::string animationName, ecs::IAnimation animation) override
                + std::string getCurrentAnimation() override
                + void useAnimation(std::string animationName) override
            }
            ecs.component.ARenderable <|-- Renderable
        }

        namespace system {
            class Graphics {
                + Graphics()
                + ~Graphics()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AGraphics <|-- Graphics
        }
    }

    namespace sdl {
        class Graphical {
            + Graphical(Universe& universe)
            + ~Graphical()
            + LIBTYPE getType() override
            + ecs::component::ARenderable createRenderable(std::vector<std::string> paths, bool isAnimated = false) override
            + ecs::IAnimation createAnimation(int index, int frame, int speed) override
        }
        graphical.AGraphical <|-- Graphical

        namespace component {
            ' using SDL_Angle = double
            class Renderable {
                - SDL_Texture* _texture
                - SDL_rect _srcRect, _destRect
                - SDL_RenderFlip _spriteFlip
                - SDL_Angle _angle
                - bool _animated
                - int _frame
                - int _speed
                - int _animIndex
                - std::map<std::string, ecs::IAnimation> _animations {}


                + Sprite(std::string name, bool isAnimated = false)
                + ~Sprite()
                + void setTexture(std::string name) override
                + void setAnimation(std::string animationName, ecs::IAnimation animation) override
                + std::string getCurrentAnimation() override
                + void useAnimation(std::string animationName) override
            }
            ecs.component.ARenderable <|-- Renderable
        }

        namespace system {
            class Graphics {
                + Graphics()
                + ~Graphics()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AGraphics <|-- Graphics
        }
    }

    namespace ncurses {
        class Graphical {
            + Graphical(Universe& universe)
            + ~Graphical()
            + LIBTYPE getType() override
            + ecs::component::ARenderable createRenderable(std::vector<std::string> paths, bool isAnimated = false) override
            + ecs::IAnimation createAnimation(int index, int frame, int speed) override
        }
        graphical.AGraphical <|-- Graphical

        class Texture {
            - char _character
            - int _foreground
            - int _background

            + Texture(char c, int f, int b)
            + ~Texture()
            + char getCharacter()
            + int getColorPair()
        }

        namespace component {
            class Renderable {
                - std::map<int, std::map<int, Texture>> _texture
                - Rect _srcRect, _destRect
                - bool _animated
                - int _frame
                - int _speed
                - int _animIndex
                - std::map<std::string, ecs::IAnimation> _animations {}

                + Sprite(std::string name, bool isAnimated = false)
                + ~Sprite()
                + void setAnimation(std::string animationName, ecs::IAnimation animation) override
                + std::string getCurrentAnimation() override
                + void useAnimation(std::string animationName) override
            }
            ecs.component.ARenderable <|-- Renderable
        }

        namespace system {
            class Graphics {
                + Graphics()
                + ~Graphics()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AGraphics <|-- Graphics
        }

        class Rect {
            + int x
            + int y
            + int h
            + int w

            + Rect(int x, int y, int h, int w)
            + ~Rect()
        }
        graphical.ncurses.component.Renderable <-- Rect
    }
}

namespace game {
    interface IGame {
        + virtual ~IGame() = 0
    }

    abstract AGame {
        # Universe& _universe
        # IGraphical& _graph

        + AGame(Universe& universe, IGraphical& graph)
        + virtual ~AGame() = 0
    }
    IGame <|-- AGame

    namespace nibbler {
        class Game {
            + Game(Universe& universe, IGraphical& graph)
            + ~Game()
        }
        game.AGame <|-- Game

        namespace component {
            
        }

        namespace system {
            class Player {
                + Player()
                + ~Player()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.APlayer <|-- Player

            class AI {
                + AI()
                + ~AI()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AAI <|-- AI

            class Follow {
                + Follow()
                + ~Follow()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AFollow <|-- Follow
        }
    }

    namespace pacman {
        class Game {
            + Game(Universe& universe, IGraphical& graph)
            + ~Game()
        }
        game.AGame <|-- Game

        namespace component {
            
        }
        namespace system {
            class Player {
                + Player()
                + ~Player()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.APlayer <|-- Player

            class AI {
                + AI()
                + ~AI()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AAI <|-- AI

            class Follow {
                + Follow()
                + ~Follow()
                + void init() override
                + void update() override
                + void render() override
            }
            ecs.system.AFollow <|-- Follow
        }
    }
}

namespace core {
    class Core {
    }
}

namespace event {
    class Event {
        + Event()
        + ~Event()
    }

    class InputEvent {

    }
    event.Event <|-- InputEvent

    class CollisionEvent {

    }
    event.Event <|-- CollisionEvent

    abstract AFunctionHandler {
        - virtual void call(Event* event) = 0
        + void exec(Event* event)
    }

    ' template<class T, class EventType>
    class FunctionHandler {
        - T* _instance
        - MemberFunction _memberFunction

        ' typedef void (T::*MemberFunction)(EventType*)

        + FunctionHandler(T* instance, MemberFunction memberFunction)
        + void call(Event* event) override
    }
    event.AFunctionHandler <|-- FunctionHandler

    ' typedef std::list<AFunctionHandler*> HandlerList
    class EventBus {
        - std::map<std::type_index, HandlerList*> _subscribers

        + template<class T, class EventType> void subscribe(T * instance, void (T::*memberFunction)(EventType *))
        + template<typename EventType> void publish(EventType* event) 
    }
}

@enduml